version: '3'
services:
  ### POSTGRES database for w2m challenge
  db-w2m:
    container_name: db-w2m
    image: postgres:16.3
    restart: unless-stopped
    environment:
      POSTGRES_DB: w2m
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - 5434:5434
    expose:
      - 5434
    command: -p 5434

  ### Zookeeper
  zookeeper:
    container_name: zookeeper
    image: confluentinc/cp-zookeeper:7.6.1
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  ### Kafka
  kafka:
    container_name: kafka
    image: confluentinc/cp-kafka:7.6.1
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

  ### Application
  w2m-app:
    container_name: w2m-app
    image: w2m-app:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      POSTGRES_DB: w2m
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      SPRING_DATASOURCE_URL: jdbc:postgresql://db-w2m:5434/w2m
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:29092
    depends_on:
      - db-w2m
      - kafka