CREATE TABLE public.media (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	media_type varchar(255) NOT NULL,
	title varchar(255) NULL,
	CONSTRAINT media_media_type_check CHECK (((media_type)::text = ANY ((ARRAY['SERIE'::character varying, 'MOVIE'::character varying])::text[]))),
	CONSTRAINT media_pkey PRIMARY KEY (id)
);



CREATE TABLE public.spacecraft (
	manufacture_date date NULL,
	max_crew int4 NULL,
	max_speed float8 NULL,
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	media_id int8 NULL,
	model varchar(255) NULL,
	"name" varchar(255) NULL,
	CONSTRAINT spacecraft_pkey PRIMARY KEY (id)
);


-- public.spacecraft foreign keys

ALTER TABLE public.spacecraft ADD CONSTRAINT fkkqtkm33gxwsxcs66kanfdsx9j FOREIGN KEY (media_id) REFERENCES public.media(id);