CREATE TABLE public.users (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	password varchar(255) NULL,
	username varchar(255) NULL,
	CONSTRAINT users_pkey PRIMARY KEY (id)
);

CREATE TABLE public.authorities (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	name varchar(255) NULL,
	CONSTRAINT authorities_name_check CHECK (((name)::text = ANY ((ARRAY['READ'::character varying, 'WRITE'::character varying, 'ADMIN'::character varying])::text[]))),
	CONSTRAINT authorities_pkey PRIMARY KEY (id)
);

CREATE TABLE public.user_authority (
	user_id int8 NOT NULL,
	authority_id int8 NOT NULL
);


-- public.user_authority foreign keys

ALTER TABLE public.user_authority ADD CONSTRAINT fkhi46vu7680y1hwvmnnuh4cybx FOREIGN KEY (user_id) REFERENCES public.users(id);
ALTER TABLE public.user_authority ADD CONSTRAINT fkil6f39w6fgqh4gk855pstsnmy FOREIGN KEY (authority_id) REFERENCES public.authorities(id);